version: '3.8'

services:

  mongodb:
    image: mongo:7
    container_name: notification_mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    ports:
      - "27017:27017"

  notification-service:
    build: .
    container_name: notification_service
    ports:
      - "8088:8088"
    environment:
      MONGO_URI: mongodb://admin:admin123@mongodb:27017/?authSource=admin
    depends_on:
      - mongodb